version: '3'

services:
  server:
    # container_name: nodejs_server
    build: .
    # ports:
    #   - 3000:3000

  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - server
    ports:
      - 3000:3000
